spring.application.name=Neuralingo
spring.data.mongodb.uri=mongod
logging.level.org.slf4j=OFF
logging.level.root=ERROR
server.port=8080
springdoc.swagger-ui.url=http://localhost:8080
springdoc.swagger-ui.disable-swagger-default-url=true
jwt.secret=f7552fb532dab
# Azure Document Intelligence
azure.document.endpoint=https://volvo.cognitiveservices.azure.com/
azure.document.apiKey=

# Azure Translator
azure.translator.endpoint=
azure.translator.apiKey=4v
azure.translator.region=westeurope

azure.storage.connection-string=
azure.storage.container-name=vo

# Limit pojedynczego pliku (np. 10MB)
spring.servlet.multipart.max-file-size=100MB

# Limit ca?ego requestu (np. 15MB)
spring.servlet.multipart.max-request-size=150MB
# zamiast pe?nego stacktrace ? TYLKO pierwsza linijka
logging.exception-conversion-word=%ex{12}


